#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$DIR/.."

GRAAL_HOME=/Users/ragnardahlen/projects/graalvm/graalvm-0.24

JAVACMD=${JAVACMD:=$GRAAL_HOME/bin/java}

PROGRAM_ARGS=""
JAVA_ARGS="-Dgraal.TruffleCompilationExceptionsAreFatal=true"

for opt in "$@"
do
  case $opt in
    --dump)
        JAVA_ARGS="$JAVA_ARGS -Dgraal.Dump= -Dgraal.MethodFilter=Truffle.* -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true" ;;
    --trace-deopt)
        JAVA_ARGS="$JAVA_ARGS -XX:+TraceDeoptimization" ;;
    --disassemble)
      JAVA_ARGS="$JAVA_ARGS -XX:CompileCommand=print,*OptimizedCallTarget.callRoot -XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true" ;;
    -J*)
      opt=${opt:2}
      JAVA_ARGS="$JAVA_ARGS $opt" ;;
    *)
      PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
  esac
done


$JAVACMD $JAVA_ARGS \
         -cp "$ROOT/target/classes" \
         com.github.ragnard.shen.KLambda "$PROGRAM_ARGS"

# #        -Dgraal.Dump= -Dgraal.MethodFilter=Truffle.* -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true \

#JAVA=/Users/ragnardahlen/projects/graalvm/labsjdk1.8.0_121-jvmci-0.26/bin/java

# "$JAVA" -server \
#         -XX:+UnlockExperimentalVMOptions \
#         -XX:+EnableJVMCI \
#         -d64 \
#         -Djvmci.class.path.append=$GRAAL_HOME/lib/graal/graal.jar \
#         -Xbootclasspath/a:$GRAAL_HOME/lib/truffle/truffle-api.jar \
#         -Dgraal.Dump= -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true \
#         -Dgraal.TruffleCompilationExceptionsAreFatal=true \
#         -cp target/classes \
#         com.github.ragnard.shen.KLambda "$@"

#        -XX:CompileCommand=print,*OptimizedCallTarget.callRoot -XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true \
# -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
# -agentpath:'/Applications/YourKit Java Profiler.app/Contents/Resources/bin/mac/libyjpagent.jnilib' \


#             -XX:+TraceDeoptimization \

